import { XCircle } from "lucide-react";
import { cancelAppointment } from "@/app/actions";
import { DashboardShell } from "@/components/dashboard-shell";
import { decodeTenantId, type Appointment } from "@/lib/db";
import { tenantApi } from "@/lib/api";

const dateTime = new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" });
export default async function AppointmentsPage({ params }: { params: Promise<{ tenantId: string }> }) {
  const { tenantId } = await params;
  const decodedTenantId = decodeTenantId(tenantId);
  const appointments = (await tenantApi<Array<{ appointmentId: string; tenantId: string; customerName: string; customerPhone: string; service: string; startTime: string; endTime: string; status: Appointment["status"]; notes: string | null; createdAt: string }>>(`/api/tenants/${encodeURIComponent(decodedTenantId)}/appointments`)).map((item): Appointment => ({ appointment_id: item.appointmentId, tenant_id: item.tenantId, customer_name: item.customerName, customer_phone: item.customerPhone, service: item.service, start_time: new Date(item.startTime), end_time: new Date(item.endTime), status: item.status, notes: item.notes, created_at: new Date(item.createdAt) }));
  return <DashboardShell tenantId={tenantId}><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-teal-700">CUSTOMERS</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Appointments</h2><div className="mt-7 overflow-x-auto rounded-lg border border-black/5 bg-white shadow-sm"><table className="w-full min-w-180 text-left text-sm"><thead className="border-b border-stone-100 text-xs uppercase tracking-wider text-stone-500"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Service</th><th className="px-5 py-4">When (UTC)</th><th className="px-5 py-4">Status</th><th className="px-5 py-4" /></tr></thead><tbody>{appointments.map((appointment) => <tr key={appointment.appointment_id} className="border-b border-stone-100 last:border-0"><td className="px-5 py-4"><p className="font-medium">{appointment.customer_name}</p><p className="text-stone-500">{appointment.customer_phone}</p></td><td className="px-5 py-4">{appointment.service}</td><td className="px-5 py-4">{dateTime.format(new Date(appointment.start_time))}</td><td className="px-5 py-4 capitalize">{appointment.status}</td><td className="px-5 py-4">{appointment.status === "booked" && <form action={cancelAppointment.bind(null, decodedTenantId, appointment.appointment_id)}><button className="inline-flex items-center gap-1 text-sm font-medium text-rose-700"><XCircle size={16} /> Cancel</button></form>}</td></tr>)}{!appointments.length && <tr><td colSpan={5} className="p-10 text-center text-stone-500">No appointments yet.</td></tr>}</tbody></table></div></div></DashboardShell>;
}